import { useState, useEffect } from 'react'

export default function ApplicationBot({ isOpen, onClose, job, userProfile }) {
    const [step, setStep] = useState(0) // 0: Init, 1: Filling, 2: Success
    const [formData, setFormData] = useState({ name: '', email: '', resume: '', coverLetter: '' })

    useEffect(() => {
        if (isOpen) {
            setStep(0)
            setFormData({ name: '', email: '', resume: '', coverLetter: '' })

            // Sequence of Auto-Filling
            const timeouts = []

            // Step 1: Initialize
            timeouts.push(setTimeout(() => setStep(1), 500))

            // Step 2: Fill Name
            timeouts.push(setTimeout(() => setFormData(prev => ({ ...prev, name: userProfile.name || 'Student' })), 1000))

            // Step 3: Fill Email
            timeouts.push(setTimeout(() => setFormData(prev => ({ ...prev, email: userProfile.email || 'student@test.com' })), 1500))

            // Step 4: Attach Resume
            timeouts.push(setTimeout(() => setFormData(prev => ({ ...prev, resume: 'Resume_v2.pdf (Parsed ✅)' })), 2200))

            // Step 5: Generate Cover Letter
            timeouts.push(setTimeout(() => setFormData(prev => ({
                ...prev,
                coverLetter: `Generated by AI: I am excited to apply for the ${job.title} role at ${job.company}. My skills in ${job.skills.join(', ')} align perfectly...`
            })), 3000))

            // Step 6: Submit
            timeouts.push(setTimeout(() => setStep(2), 4500))

            // Step 7: Close
            timeouts.push(setTimeout(() => onClose(true), 6000))

            return () => timeouts.forEach(clearTimeout)
        }
    }, [isOpen, job, userProfile, onClose])

    if (!isOpen) return null

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm">
            <div className="glass-card w-full max-w-lg p-8 rounded-3xl border border-primary/30 shadow-[0_0_50px_rgba(255,0,80,0.2)] relative overflow-hidden">

                {/* Background Grid Animation */}
                <div className="absolute inset-0 bg-[url('/grid.svg')] opacity-10 animate-pulse"></div>

                {step < 2 ? (
                    <>
                        <div className="flex items-center gap-4 mb-6">
                            <div className="w-12 h-12 rounded-full bg-primary flex items-center justify-center text-2xl animate-spin-slow">
                                🤖
                            </div>
                            <div>
                                <h3 className="text-xl font-bold text-white">AI Auto-Filler</h3>
                                <p className="text-xs text-primary animate-pulse">Processing Application...</p>
                            </div>
                        </div>

                        <div className="space-y-4">
                            <div>
                                <label className="text-xs text-gray-500 uppercase">Full Name</label>
                                <div className={`h-10 border-b border-white/20 flex items-center text-lg ${formData.name ? 'text-white' : 'text-gray-700'}`}>
                                    {formData.name || <span className="animate-pulse">|</span>}
                                </div>
                            </div>
                            <div>
                                <label className="text-xs text-gray-500 uppercase">Email</label>
                                <div className={`h-10 border-b border-white/20 flex items-center text-lg ${formData.email ? 'text-white' : 'text-gray-700'}`}>
                                    {formData.email}
                                </div>
                            </div>
                            <div>
                                <label className="text-xs text-gray-500 uppercase">Resume Data</label>
                                <div className="h-10 flex items-center gap-2">
                                    {formData.resume && <span className="text-green-400">📎 {formData.resume}</span>}
                                </div>
                            </div>
                            <div>
                                <label className="text-xs text-gray-500 uppercase">AI Cover Letter</label>
                                <div className="p-3 bg-white/5 rounded-lg text-sm text-gray-300 min-h-[80px] border border-dashed border-white/10">
                                    {formData.coverLetter || <span className="animate-pulse">Writing...</span>}
                                </div>
                            </div>
                        </div>
                    </>
                ) : (
                    <div className="flex flex-col items-center justify-center py-8 text-center animate-fade-in-up">
                        <div className="w-20 h-20 bg-green-500 rounded-full flex items-center justify-center text-4xl mb-4 shadow-[0_0_30px_rgba(34,197,94,0.6)]">
                            ✓
                        </div>
                        <h3 className="text-2xl font-bold text-white mb-2">Application Sent!</h3>
                        <p className="text-gray-400">Your profile has been successfully submitted to {job.company}.</p>
                    </div>
                )}
            </div>
        </div>
    )
}
